name: ci
on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq gcc libiio-dev cppcheck shellcheck python3
      - name: run_ci
        run: sh test/run_ci.sh
